In [2]:
import pandas as pd
from binance.client import Client
client = Client()

In [3]:
info = client.get_exchange_info()
df_pairs = pd.DataFrame(info["symbols"])
df_active = df_pairs[df_pairs["status"] == "TRADING"][
    ["symbol", "baseAsset", "quoteAsset"]
]

In [4]:
all_tickers = Client().get_all_tickers()
df_tickers = pd.DataFrame(all_tickers)
df_tickers["price"] = df_tickers["price"].astype(float)

In [5]:
df_usdt = df_active[df_active['quoteAsset']=="USDT"]

In [6]:
df_merged = pd.merge(df_usdt, df_tickers, on="symbol", how="left")

In [7]:
## Known altcoins close to USDT price
altcoins = ["XRP", "DOT", "AXS", "GAS", "PROM", "PENDLE", "ORCA", "VANA", "U", "ATM", "ASR", "MOVR", "CVX", "RPL", "ZRO", "EUL"]

In [8]:
stable_coins = df_merged[(df_merged["price"] < 1.3) & (df_merged["price"] > 0.8)]['baseAsset'].to_list()
stable_coins  = [i for i in stable_coins if i not in altcoins]
stable_coins

['TUSD',
 'USDC',
 'EUR',
 'CAKE',
 'USDP',
 'FDUSD',
 'AEUR',
 'EURI',
 'XUSD',
 'USD1',
 'BFUSD',
 'USDE',
 'RLUSD',
 'USDS']

In [9]:
stable_coin_df = df_active[(df_active['quoteAsset']=="USDT") & df_active["baseAsset"].isin(stable_coins)].reset_index(drop=True)
stable_coin_symbols = stable_coin_df["symbol"].to_list()
stable_coin_symbols

['TUSDUSDT',
 'USDCUSDT',
 'EURUSDT',
 'CAKEUSDT',
 'USDPUSDT',
 'FDUSDUSDT',
 'AEURUSDT',
 'EURIUSDT',
 'XUSDUSDT',
 'USD1USDT',
 'BFUSDUSDT',
 'USDEUSDT',
 'RLUSDUSDT',
 'USDSUSDT']

In [10]:
stable_coins.append("USDT")
tri_arb_assets_df = df_active[df_active["quoteAsset"].isin(stable_coins)].reset_index(drop=True)
tri_arb_assets_df

           symbol baseAsset quoteAsset
0         BTCUSDT       BTC       USDT
1         ETHUSDT       ETH       USDT
2         BNBUSDT       BNB       USDT
3         NEOUSDT       NEO       USDT
4         LTCUSDT       LTC       USDT
..            ...       ...        ...
813  AIGENSYNUSDC  AIGENSYN       USDC
814    GENIUSUSDT    GENIUS       USDT
815    GENIUSUSDC    GENIUS       USDC
816       OPGUSDT       OPG       USDT
817       OPGUSDC       OPG       USDC

[818 rows x 3 columns]

In [11]:
tri_arb_assets_df.groupby("quoteAsset")["symbol"].count()

quoteAsset
EUR       29
EURI       3
FDUSD     37
RLUSD      1
USD1      27
USDC     289
USDS       2
USDT     430
Name: symbol, dtype: int64

In [12]:
stable_coins_low_vol = [i for i in stable_coins if i not in ["USDT", "USDC"]]
tri_arb_low_vol_assets_df = df_active[df_active["quoteAsset"].isin(stable_coins_low_vol)].reset_index(drop=True)
tri_arb_low_vol_assets_df

      symbol baseAsset quoteAsset
0     BTCEUR       BTC        EUR
1     ETHEUR       ETH        EUR
2     BNBEUR       BNB        EUR
3     XRPEUR       XRP        EUR
4    LINKEUR      LINK        EUR
..       ...       ...        ...
94   ETHUSDS       ETH       USDS
95  币安人生USD1      币安人生       USD1
96  CHIPUSD1      CHIP       USD1
97  XAUTUSD1      XAUT       USD1
98   TONUSD1       TON       USD1

[99 rows x 3 columns]

In [13]:
all_24h_stats = client.get_ticker()
df_all = pd.DataFrame(all_24h_stats)
all_vol = df_all[["symbol", "weightedAvgPrice", "volume"]].astype({"weightedAvgPrice": float, "volume": float})

all_vol["$vol"] = all_vol["weightedAvgPrice"]*all_vol["volume"]

In [14]:
universe_wo_vol = pd.merge(tri_arb_low_vol_assets_df, all_vol, on="symbol", how="left")
universe_wo_vol

,symbol,baseAsset,quoteAsset,weightedAvgPrice,volume,$vol
0,BTCEUR,BTC,EUR,53419.936211,3.521822e+02,1.881355e+07
1,ETHEUR,ETH,EUR,1416.709961,6.070593e+03,8.600270e+06
2,BNBEUR,BNB,EUR,510.083155,1.040735e+03,5.308614e+05
3,XRPEUR,XRP,EUR,0.968426,3.124875e+06,3.026211e+06
4,LINKEUR,LINK,EUR,6.699281,2.054164e+04,1.376142e+05
...,...,...,...,...,...,...
94,ETHUSDS,ETH,USDS,1637.758503,6.282510e+01,1.028923e+05
95,币安人生USD1,币安人生,USD1,0.709817,1.591820e+04,1.129902e+04
96,CHIPUSD1,CHIP,USD1,0.033464,2.185940e+05,7.315014e+03
97,XAUTUSD1,XAUT,USD1,4188.869292,5.566800e+00,2.331860e+04
98,TONUSD1,TON,USD1,1.686867,3.085470e+03,5.204778e+03

In [15]:
ex_list = df_active[(df_active["quoteAsset"]=="USDT") & (df_active["baseAsset"].isin(stable_coins_low_vol))]["symbol"].to_list()
stable_ex_df = all_vol[all_vol["symbol"].isin(ex_list)]
stable_ex_df.rename(columns={"symbol":"ex_symbol", "weightedAvgPrice": "usdtPrice", "volume": "ex_volume"}, inplace=True)
stable_ex_df["quoteAsset"] = stable_ex_df["ex_symbol"].str[:-4]
stable_ex_df.reset_index(drop=True, inplace=True)

stable_ex_df

    ex_symbol  usdtPrice     ex_volume          $vol quoteAsset
0    TUSDUSDT   1.000046  1.350300e+05  1.350362e+05       TUSD
1     EURUSDT   1.155644  1.952146e+07  2.255985e+07        EUR
2    CAKEUSDT   1.306800  1.423449e+06  1.860163e+06       CAKE
3    USDPUSDT   1.000181  4.444000e+03  4.444805e+03       USDP
4   FDUSDUSDT   0.998217  2.008772e+07  2.005191e+07      FDUSD
5    AEURUSDT   1.148436  7.192000e+02  8.259551e+02       AEUR
6    EURIUSDT   1.155142  1.730533e+06  1.999012e+06       EURI
7    XUSDUSDT   1.000829  2.877336e+06  2.879722e+06       XUSD
8    USD1USDT   0.999531  1.740512e+08  1.739695e+08       USD1
9   BFUSDUSDT   0.999376  8.415836e+06  8.410584e+06      BFUSD
10   USDEUSDT   0.999908  4.123579e+06  4.123199e+06       USDE
11  RLUSDUSDT   1.000744  1.684528e+07  1.685781e+07      RLUSD
12   USDSUSDT   1.000566  3.173370e+05  3.175166e+05       USDS

In [16]:
universe = pd.merge(universe_wo_vol, stable_ex_df, on="quoteAsset", how="left")
universe["weightedAvgPrice"] = universe["weightedAvgPrice"].astype(float)
universe["volume"] = universe["volume"].astype(float)

universe["volume$"] = universe["weightedAvgPrice"] * universe["volume"] 


universe = universe[universe["volume$"]>100000]
universe.index.name = "no."
sorted_universe = universe.sort_values(by="weightedAvgPrice", ascending=False).reset_index(drop=True)
sorted_universe

,symbol,baseAsset,quoteAsset,weightedAvgPrice,volume,$vol_x,ex_symbol,usdtPrice,ex_volume,$vol_y,volume$
0,BTCFDUSD,BTC,FDUSD,61913.053470,9.304773e+02,5.760869e+07,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,5.760869e+07
1,BTCUSDS,BTC,USDS,61798.826369,1.720270e+00,1.063107e+05,USDSUSDT,1.000566,317337.0,3.175166e+05,1.063107e+05
2,BTCUSD1,BTC,USD1,61763.497505,2.319084e+03,1.432348e+08,USD1USDT,0.999531,174051171.0,1.739695e+08,1.432348e+08
3,BTCEURI,BTC,EURI,53553.510367,2.556300e+00,1.368988e+05,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.368988e+05
4,BTCEUR,BTC,EUR,53419.936211,3.521822e+02,1.881355e+07,EURUSDT,1.155644,19521458.9,2.255985e+07,1.881355e+07
5,ETHFDUSD,ETH,FDUSD,1640.552066,1.291600e+04,2.118937e+07,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.118937e+07
6,ETHUSD1,ETH,USD1,1638.314807,4.558979e+04,7.469043e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,7.469043e+07
7,ETHUSDS,ETH,USDS,1637.758503,6.282510e+01,1.028923e+05,USDSUSDT,1.000566,317337.0,3.175166e+05,1.028923e+05
8,ETHEURI,ETH,EURI,1421.458802,8.652420e+01,1.229906e+05,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.229906e+05
9,ETHEUR,ETH,EUR,1416.709961,6.070593e+03,8.600270e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,8.600270e+06
10,BNBFDUSD,BNB,FDUSD,591.020155,3.077514e+03,1.818873e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.818873e+06
11,BNBUSD1,BNB,USD1,589.914185,3.308300e+04,1.951613e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,1.951613e+07
12,BNBEUR,BNB,EUR,510.083155,1.040735e+03,5.308614e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,5.308614e+05
13,ZECUSD1,ZEC,USD1,431.755888,6.457250e+02,2.787956e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,2.787956e+05
14,BCHFDUSD,BCH,FDUSD,200.442172,1.193438e+03,2.392153e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.392153e+05
15,SOLFDUSD,SOL,FDUSD,64.647111,1.151701e+05,7.445414e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,7.445414e+06
16,SOLUSD1,SOL,USD1,64.506703,2.869215e+05,1.850836e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,1.850836e+07
17,SOLEUR,SOL,EUR,55.687968,4.475990e+04,2.492588e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,2.492588e+06
18,LTCEUR,LTC,EUR,36.793413,6.356678e+03,2.338839e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,2.338839e+05
19,LINKEUR,LINK,EUR,6.699281,2.054164e+04,1.376142e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.376142e+05
20,NEAREUR,NEAR,EUR,1.833859,1.912051e+05,3.506432e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,3.506432e+05
21,XRPUSD1,XRP,USD1,1.120741,4.747518e+06,5.320737e+06,USD1USDT,0.999531,174051171.0,1.739695e+08,5.320737e+06
22,XRPFDUSD,XRP,FDUSD,1.120679,1.367383e+06,1.532397e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.532397e+06
23,XRPRLUSD,XRP,RLUSD,1.117955,1.103430e+06,1.233585e+06,RLUSDUSDT,1.000744,16845280.0,1.685781e+07,1.233585e+06
24,EUREURI,EUR,EURI,1.000303,1.841957e+06,1.842516e+06,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.842516e+06
25,XRPEUR,XRP,EUR,0.968426,3.124875e+06,3.026211e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,3.026211e+06
26,DOTEUR,DOT,EUR,0.816122,2.230289e+05,1.820187e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.820187e+05
27,SUIFDUSD,SUI,FDUSD,0.746219,2.628791e+05,1.961655e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.961655e+05
28,SUIUSD1,SUI,USD1,0.745900,6.953686e+05,5.186751e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,5.186751e+05
29,SUIEUR,SUI,EUR,0.645779,2.074825e+05,1.339877e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.339877e+05
30,WLDFDUSD,WLD,FDUSD,0.488282,5.759268e+05,2.812144e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.812144e+05
31,WLDEUR,WLD,EUR,0.414264,4.253641e+05,1.762132e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.762132e+05
32,TRXEUR,TRX,EUR,0.279058,5.243310e+05,1.463185e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.463185e+05
33,ADAFDUSD,ADA,FDUSD,0.163792,2.277231e+06,3.729916e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,3.729916e+05
34,XLMEUR,XLM,EUR,0.161898,1.172962e+06,1.899004e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.899004e+05
35,ADAEUR,ADA,EUR,0.140962,6.164884e+06,8.690119e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,8.690119e+05
36,ERAFDUSD,ERA,FDUSD,0.096938,2.726927e+06,2.643427e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.643427e+05
37,DOGEFDUSD,DOGE,FDUSD,0.084265,2.505350e+07,2.111139e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.111139e+06
38,DOGEUSD1,DOGE,USD1,0.084238,7.244663e+06,6.102748e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,6.102748e+05
39,ENAFDUSD,ENA,FDUSD,0.078116,2.753814e+06,2.151182e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.151182e+05
40,FFFDUSD,FF,FDUSD,0.076954,1.613947e+06,1.242002e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.242002e+05
41,POLFDUSD,POL,FDUSD,0.074591,2.048407e+06,1.527921e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.527921e+05
42,DOGEEUR,DOGE,EUR,0.072826,6.737964e+06,4.906961e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,4.906961e+05
43,WLFIUSD1,WLFI,USD1,0.059440,1.307461e+07,7.771581e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,7.771581e+05
44,PEPEEUR,PEPE,EUR,0.000002,8.252563e+10,1.964110e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.964110e+05

In [17]:
altcoins = ["BTC", "SOL", "ETH", "BNB", "ZEC", "XRP","SUI", "LINK"]
altcoin_symbols = [i+"USDT" for i in altcoins]
altcoin_symbols_df = all_vol[all_vol["symbol"].isin(altcoin_symbols)]
altcoin_symbols_df.rename(columns={"symbol":"usdt_ob", "weightedAvgPrice": "usdtAssetPrice", "volume": "ob2_volume"}, inplace=True)

altcoin_symbols_df["baseAsset"] = altcoin_symbols_df["usdt_ob"].str.replace("USDT", "", regex=False)

altcoin_symbols_df

       usdt_ob  usdtAssetPrice    ob2_volume          $vol baseAsset
11     BTCUSDT    61715.558143  1.565000e+04  9.658485e+08       BTC
12     ETHUSDT     1636.529145  2.734128e+05  4.474481e+08       ETH
98     BNBUSDT      589.533878  1.117128e+05  6.585847e+07       BNB
306    XRPUSDT        1.118376  1.109527e+08  1.240869e+08       XRP
431   LINKUSDT        7.743119  1.896963e+06  1.468841e+07      LINK
477    ZECUSDT      430.482430  4.291913e+05  1.847593e+08       ZEC
779    SOLUSDT       64.389632  2.778440e+06  1.789027e+08       SOL
2205   SUIUSDT        0.746339  3.231317e+07  2.411657e+07       SUI

In [18]:
universe_w_tri_asset = pd.merge(sorted_universe, altcoin_symbols_df, on="baseAsset", how="left")
universe_w_tri_asset

,symbol,baseAsset,quoteAsset,weightedAvgPrice,volume,$vol_x,ex_symbol,usdtPrice,ex_volume,$vol_y,volume$,usdt_ob,usdtAssetPrice,ob2_volume,$vol
0,BTCFDUSD,BTC,FDUSD,61913.053470,9.304773e+02,5.760869e+07,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,5.760869e+07,BTCUSDT,61715.558143,1.565000e+04,9.658485e+08
1,BTCUSDS,BTC,USDS,61798.826369,1.720270e+00,1.063107e+05,USDSUSDT,1.000566,317337.0,3.175166e+05,1.063107e+05,BTCUSDT,61715.558143,1.565000e+04,9.658485e+08
2,BTCUSD1,BTC,USD1,61763.497505,2.319084e+03,1.432348e+08,USD1USDT,0.999531,174051171.0,1.739695e+08,1.432348e+08,BTCUSDT,61715.558143,1.565000e+04,9.658485e+08
3,BTCEURI,BTC,EURI,53553.510367,2.556300e+00,1.368988e+05,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.368988e+05,BTCUSDT,61715.558143,1.565000e+04,9.658485e+08
4,BTCEUR,BTC,EUR,53419.936211,3.521822e+02,1.881355e+07,EURUSDT,1.155644,19521458.9,2.255985e+07,1.881355e+07,BTCUSDT,61715.558143,1.565000e+04,9.658485e+08
5,ETHFDUSD,ETH,FDUSD,1640.552066,1.291600e+04,2.118937e+07,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.118937e+07,ETHUSDT,1636.529145,2.734128e+05,4.474481e+08
6,ETHUSD1,ETH,USD1,1638.314807,4.558979e+04,7.469043e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,7.469043e+07,ETHUSDT,1636.529145,2.734128e+05,4.474481e+08
7,ETHUSDS,ETH,USDS,1637.758503,6.282510e+01,1.028923e+05,USDSUSDT,1.000566,317337.0,3.175166e+05,1.028923e+05,ETHUSDT,1636.529145,2.734128e+05,4.474481e+08
8,ETHEURI,ETH,EURI,1421.458802,8.652420e+01,1.229906e+05,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.229906e+05,ETHUSDT,1636.529145,2.734128e+05,4.474481e+08
9,ETHEUR,ETH,EUR,1416.709961,6.070593e+03,8.600270e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,8.600270e+06,ETHUSDT,1636.529145,2.734128e+05,4.474481e+08
10,BNBFDUSD,BNB,FDUSD,591.020155,3.077514e+03,1.818873e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.818873e+06,BNBUSDT,589.533878,1.117128e+05,6.585847e+07
11,BNBUSD1,BNB,USD1,589.914185,3.308300e+04,1.951613e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,1.951613e+07,BNBUSDT,589.533878,1.117128e+05,6.585847e+07
12,BNBEUR,BNB,EUR,510.083155,1.040735e+03,5.308614e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,5.308614e+05,BNBUSDT,589.533878,1.117128e+05,6.585847e+07
13,ZECUSD1,ZEC,USD1,431.755888,6.457250e+02,2.787956e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,2.787956e+05,ZECUSDT,430.482430,4.291913e+05,1.847593e+08
14,BCHFDUSD,BCH,FDUSD,200.442172,1.193438e+03,2.392153e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.392153e+05,NaN,NaN,NaN,NaN
15,SOLFDUSD,SOL,FDUSD,64.647111,1.151701e+05,7.445414e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,7.445414e+06,SOLUSDT,64.389632,2.778440e+06,1.789027e+08
16,SOLUSD1,SOL,USD1,64.506703,2.869215e+05,1.850836e+07,USD1USDT,0.999531,174051171.0,1.739695e+08,1.850836e+07,SOLUSDT,64.389632,2.778440e+06,1.789027e+08
17,SOLEUR,SOL,EUR,55.687968,4.475990e+04,2.492588e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,2.492588e+06,SOLUSDT,64.389632,2.778440e+06,1.789027e+08
18,LTCEUR,LTC,EUR,36.793413,6.356678e+03,2.338839e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,2.338839e+05,NaN,NaN,NaN,NaN
19,LINKEUR,LINK,EUR,6.699281,2.054164e+04,1.376142e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.376142e+05,LINKUSDT,7.743119,1.896963e+06,1.468841e+07
20,NEAREUR,NEAR,EUR,1.833859,1.912051e+05,3.506432e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,3.506432e+05,NaN,NaN,NaN,NaN
21,XRPUSD1,XRP,USD1,1.120741,4.747518e+06,5.320737e+06,USD1USDT,0.999531,174051171.0,1.739695e+08,5.320737e+06,XRPUSDT,1.118376,1.109527e+08,1.240869e+08
22,XRPFDUSD,XRP,FDUSD,1.120679,1.367383e+06,1.532397e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.532397e+06,XRPUSDT,1.118376,1.109527e+08,1.240869e+08
23,XRPRLUSD,XRP,RLUSD,1.117955,1.103430e+06,1.233585e+06,RLUSDUSDT,1.000744,16845280.0,1.685781e+07,1.233585e+06,XRPUSDT,1.118376,1.109527e+08,1.240869e+08
24,EUREURI,EUR,EURI,1.000303,1.841957e+06,1.842516e+06,EURIUSDT,1.155142,1730533.1,1.999012e+06,1.842516e+06,NaN,NaN,NaN,NaN
25,XRPEUR,XRP,EUR,0.968426,3.124875e+06,3.026211e+06,EURUSDT,1.155644,19521458.9,2.255985e+07,3.026211e+06,XRPUSDT,1.118376,1.109527e+08,1.240869e+08
26,DOTEUR,DOT,EUR,0.816122,2.230289e+05,1.820187e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.820187e+05,NaN,NaN,NaN,NaN
27,SUIFDUSD,SUI,FDUSD,0.746219,2.628791e+05,1.961655e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.961655e+05,SUIUSDT,0.746339,3.231317e+07,2.411657e+07
28,SUIUSD1,SUI,USD1,0.745900,6.953686e+05,5.186751e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,5.186751e+05,SUIUSDT,0.746339,3.231317e+07,2.411657e+07
29,SUIEUR,SUI,EUR,0.645779,2.074825e+05,1.339877e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.339877e+05,SUIUSDT,0.746339,3.231317e+07,2.411657e+07
30,WLDFDUSD,WLD,FDUSD,0.488282,5.759268e+05,2.812144e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.812144e+05,NaN,NaN,NaN,NaN
31,WLDEUR,WLD,EUR,0.414264,4.253641e+05,1.762132e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.762132e+05,NaN,NaN,NaN,NaN
32,TRXEUR,TRX,EUR,0.279058,5.243310e+05,1.463185e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.463185e+05,NaN,NaN,NaN,NaN
33,ADAFDUSD,ADA,FDUSD,0.163792,2.277231e+06,3.729916e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,3.729916e+05,NaN,NaN,NaN,NaN
34,XLMEUR,XLM,EUR,0.161898,1.172962e+06,1.899004e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.899004e+05,NaN,NaN,NaN,NaN
35,ADAEUR,ADA,EUR,0.140962,6.164884e+06,8.690119e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,8.690119e+05,NaN,NaN,NaN,NaN
36,ERAFDUSD,ERA,FDUSD,0.096938,2.726927e+06,2.643427e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.643427e+05,NaN,NaN,NaN,NaN
37,DOGEFDUSD,DOGE,FDUSD,0.084265,2.505350e+07,2.111139e+06,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.111139e+06,NaN,NaN,NaN,NaN
38,DOGEUSD1,DOGE,USD1,0.084238,7.244663e+06,6.102748e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,6.102748e+05,NaN,NaN,NaN,NaN
39,ENAFDUSD,ENA,FDUSD,0.078116,2.753814e+06,2.151182e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,2.151182e+05,NaN,NaN,NaN,NaN
40,FFFDUSD,FF,FDUSD,0.076954,1.613947e+06,1.242002e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.242002e+05,NaN,NaN,NaN,NaN
41,POLFDUSD,POL,FDUSD,0.074591,2.048407e+06,1.527921e+05,FDUSDUSDT,0.998217,20087716.0,2.005191e+07,1.527921e+05,NaN,NaN,NaN,NaN
42,DOGEEUR,DOGE,EUR,0.072826,6.737964e+06,4.906961e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,4.906961e+05,NaN,NaN,NaN,NaN
43,WLFIUSD1,WLFI,USD1,0.059440,1.307461e+07,7.771581e+05,USD1USDT,0.999531,174051171.0,1.739695e+08,7.771581e+05,NaN,NaN,NaN,NaN
44,PEPEEUR,PEPE,EUR,0.000002,8.252563e+10,1.964110e+05,EURUSDT,1.155644,19521458.9,2.255985e+07,1.964110e+05,NaN,NaN,NaN,NaN

In [22]:
signal = ['symbol', 'baseAsset', 'weightedAvgPrice', 'usdtPrice' , 'volume$', 'usdt_ob','usdtAssetPrice', '$vol']
arb_in_universe = universe_w_tri_asset[signal].dropna()

arb_in_universe = arb_in_universe.astype({"weightedAvgPrice": float, "usdtPrice": float})

arb_in_universe["implied_usdt_price"] = arb_in_universe["weightedAvgPrice"] * arb_in_universe["usdtPrice"]

arb_in_universe

,symbol,baseAsset,weightedAvgPrice,usdtPrice,volume$,usdt_ob,usdtAssetPrice,$vol,implied_usdt_price
0,BTCFDUSD,BTC,61913.053470,0.998217,5.760869e+07,BTCUSDT,61715.558143,9.658485e+08,61802.686642
1,BTCUSDS,BTC,61798.826369,1.000566,1.063107e+05,BTCUSDT,61715.558143,9.658485e+08,61833.803887
2,BTCUSD1,BTC,61763.497505,0.999531,1.432348e+08,BTCUSDT,61715.558143,9.658485e+08,61734.526719
3,BTCEURI,BTC,53553.510367,1.155142,1.368988e+05,BTCUSDT,61715.558143,9.658485e+08,61861.920318
4,BTCEUR,BTC,53419.936211,1.155644,1.881355e+07,BTCUSDT,61715.558143,9.658485e+08,61734.406327
5,ETHFDUSD,ETH,1640.552066,0.998217,2.118937e+07,ETHUSDT,1636.529145,4.474481e+08,1637.627602
6,ETHUSD1,ETH,1638.314807,0.999531,7.469043e+07,ETHUSDT,1636.529145,4.474481e+08,1637.546339
7,ETHUSDS,ETH,1637.758503,1.000566,1.028923e+05,ETHUSDT,1636.529145,4.474481e+08,1638.685458
8,ETHEURI,ETH,1421.458802,1.155142,1.229906e+05,ETHUSDT,1636.529145,4.474481e+08,1641.987062
9,ETHEUR,ETH,1416.709961,1.155644,8.600270e+06,ETHUSDT,1636.529145,4.474481e+08,1637.211771
10,BNBFDUSD,BNB,591.020155,0.998217,1.818873e+06,BNBUSDT,589.533878,6.585847e+07,589.966596
11,BNBUSD1,BNB,589.914185,0.999531,1.951613e+07,BNBUSDT,589.533878,6.585847e+07,589.637480
12,BNBEUR,BNB,510.083155,1.155644,5.308614e+05,BNBUSDT,589.533878,6.585847e+07,589.474323
13,ZECUSD1,ZEC,431.755888,0.999531,2.787956e+05,ZECUSDT,430.482430,1.847593e+08,431.553368
15,SOLFDUSD,SOL,64.647111,0.998217,7.445414e+06,SOLUSDT,64.389632,1.789027e+08,64.531870
16,SOLUSD1,SOL,64.506703,0.999531,1.850836e+07,SOLUSDT,64.389632,1.789027e+08,64.476446
17,SOLEUR,SOL,55.687968,1.155644,2.492588e+06,SOLUSDT,64.389632,1.789027e+08,64.355442
19,LINKEUR,LINK,6.699281,1.155644,1.376142e+05,LINKUSDT,7.743119,1.468841e+07,7.741981
21,XRPUSD1,XRP,1.120741,0.999531,5.320737e+06,XRPUSDT,1.118376,1.240869e+08,1.120215
22,XRPFDUSD,XRP,1.120679,0.998217,1.532397e+06,XRPUSDT,1.118376,1.240869e+08,1.118681
23,XRPRLUSD,XRP,1.117955,1.000744,1.233585e+06,XRPUSDT,1.118376,1.240869e+08,1.118786
25,XRPEUR,XRP,0.968426,1.155644,3.026211e+06,XRPUSDT,1.118376,1.240869e+08,1.119156
27,SUIFDUSD,SUI,0.746219,0.998217,1.961655e+05,SUIUSDT,0.746339,2.411657e+07,0.744889
28,SUIUSD1,SUI,0.745900,0.999531,5.186751e+05,SUIUSDT,0.746339,2.411657e+07,0.745550
29,SUIEUR,SUI,0.645779,1.155644,1.339877e+05,SUIUSDT,0.746339,2.411657e+07,0.746290

In [23]:
print(altcoin_symbols_df['usdt_ob'].tolist())

['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'LINKUSDT', 'ZECUSDT', 'SOLUSDT', 'SUIUSDT']

In [25]:
#arb_in_universe['alpha'] = abs((arb_in_universe['usdtAssetPrice'] - arb_in_universe['implied_usdt_price'])/arb_in_universe['usdtAssetPrice'])
# price difference doesn't matter how fast it differs matter

arb_in_universe['alpha_rate'] = abs((arb_in_universe['$vol'] - arb_in_universe['volume$']))

arb_in_universe.sort_values(by='alpha_rate', ascending=False).reset_index(drop=True)

,symbol,baseAsset,weightedAvgPrice,usdtPrice,volume$,usdt_ob,usdtAssetPrice,$vol,implied_usdt_price,alpha_rate
0,BTCUSDS,BTC,61798.826369,1.000566,1.063107e+05,BTCUSDT,61715.558143,9.658485e+08,61833.803887,9.657422e+08
1,BTCEURI,BTC,53553.510367,1.155142,1.368988e+05,BTCUSDT,61715.558143,9.658485e+08,61861.920318,9.657116e+08
2,BTCEUR,BTC,53419.936211,1.155644,1.881355e+07,BTCUSDT,61715.558143,9.658485e+08,61734.406327,9.470350e+08
3,BTCFDUSD,BTC,61913.053470,0.998217,5.760869e+07,BTCUSDT,61715.558143,9.658485e+08,61802.686642,9.082399e+08
4,BTCUSD1,BTC,61763.497505,0.999531,1.432348e+08,BTCUSDT,61715.558143,9.658485e+08,61734.526719,8.226138e+08
5,ETHUSDS,ETH,1637.758503,1.000566,1.028923e+05,ETHUSDT,1636.529145,4.474481e+08,1638.685458,4.473452e+08
6,ETHEURI,ETH,1421.458802,1.155142,1.229906e+05,ETHUSDT,1636.529145,4.474481e+08,1641.987062,4.473251e+08
7,ETHEUR,ETH,1416.709961,1.155644,8.600270e+06,ETHUSDT,1636.529145,4.474481e+08,1637.211771,4.388478e+08
8,ETHFDUSD,ETH,1640.552066,0.998217,2.118937e+07,ETHUSDT,1636.529145,4.474481e+08,1637.627602,4.262587e+08
9,ETHUSD1,ETH,1638.314807,0.999531,7.469043e+07,ETHUSDT,1636.529145,4.474481e+08,1637.546339,3.727576e+08
10,ZECUSD1,ZEC,431.755888,0.999531,2.787956e+05,ZECUSDT,430.482430,1.847593e+08,431.553368,1.844805e+08
11,SOLEUR,SOL,55.687968,1.155644,2.492588e+06,SOLUSDT,64.389632,1.789027e+08,64.355442,1.764101e+08
12,SOLFDUSD,SOL,64.647111,0.998217,7.445414e+06,SOLUSDT,64.389632,1.789027e+08,64.531870,1.714573e+08
13,SOLUSD1,SOL,64.506703,0.999531,1.850836e+07,SOLUSDT,64.389632,1.789027e+08,64.476446,1.603943e+08
14,XRPRLUSD,XRP,1.117955,1.000744,1.233585e+06,XRPUSDT,1.118376,1.240869e+08,1.118786,1.228533e+08
15,XRPFDUSD,XRP,1.120679,0.998217,1.532397e+06,XRPUSDT,1.118376,1.240869e+08,1.118681,1.225545e+08
16,XRPEUR,XRP,0.968426,1.155644,3.026211e+06,XRPUSDT,1.118376,1.240869e+08,1.119156,1.210607e+08
17,XRPUSD1,XRP,1.120741,0.999531,5.320737e+06,XRPUSDT,1.118376,1.240869e+08,1.120215,1.187661e+08
18,BNBEUR,BNB,510.083155,1.155644,5.308614e+05,BNBUSDT,589.533878,6.585847e+07,589.474323,6.532761e+07
19,BNBFDUSD,BNB,591.020155,0.998217,1.818873e+06,BNBUSDT,589.533878,6.585847e+07,589.966596,6.403960e+07
20,BNBUSD1,BNB,589.914185,0.999531,1.951613e+07,BNBUSDT,589.533878,6.585847e+07,589.637480,4.634235e+07
21,SUIEUR,SUI,0.645779,1.155644,1.339877e+05,SUIUSDT,0.746339,2.411657e+07,0.746290,2.398258e+07
22,SUIFDUSD,SUI,0.746219,0.998217,1.961655e+05,SUIUSDT,0.746339,2.411657e+07,0.744889,2.392040e+07
23,SUIUSD1,SUI,0.745900,0.999531,5.186751e+05,SUIUSDT,0.746339,2.411657e+07,0.745550,2.359789e+07
24,LINKEUR,LINK,6.699281,1.155644,1.376142e+05,LINKUSDT,7.743119,1.468841e+07,7.741981,1.455080e+07

In [166]:
print(arb_in_universe.sort_values(by='alpha', ascending=False).reset_index(drop=True)["symbol"].to_list())

['ZECUSD1', 'XRPUSD1', 'XRPEUR', 'SUIFDUSD', 'SOLUSD1', 'XRPFDUSD', 'XRPRLUSD', 'SUIEUR', 'SOLFDUSD', 'BNBFDUSD', 'BTCFDUSD', 'SUIUSD1', 'ETHUSD1', 'ETHFDUSD', 'SOLEUR', 'ETHEUR', 'BNBUSD1', 'BTCEUR', 'BTCUSD1', 'LINKEUR', 'BNBEUR', 'BTCEURI']

In [171]:
print(arb_in_universe["usdt_ob"].unique())

<ArrowStringArray>
[ 'BTCUSDT',  'ETHUSDT',  'BNBUSDT',  'ZECUSDT',  'SOLUSDT', 'LINKUSDT',
  'XRPUSDT',  'SUIUSDT']
Length: 8, dtype: str

In [26]:
arb_in_universe[arb_in_universe['symbol'].isin(['EURIUSDT','BTCEURI','EURIUSDT'])]

,symbol,baseAsset,weightedAvgPrice,usdtPrice,volume$,usdt_ob,usdtAssetPrice,$vol,implied_usdt_price,alpha_rate
3,BTCEURI,BTC,53553.510367,1.155142,136898.83855,BTCUSDT,61715.558143,9.658485e+08,61861.920318,9.657116e+08